
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ASUS
 */
public class Admin extends javax.swing.JFrame {

    Baglanti baglanti = new Baglanti();
    ResultSet myRs = null;
    ResultSet myRs_sanatci = null;
    ResultSet myRs_k_s = null;
    ResultSet myRs_album = null;
    ResultSet myRs_tur = null;
    ResultSet myRs_s_s = null;
    ResultSet myRs_a_a = null;
    ResultSet myRs_a_s = null;
    DefaultTableModel model;

    public Admin() throws SQLException {
        myRs = baglanti.yap("sarki");
        myRs_k_s = baglanti.yap("kullanici_sarki");
        myRs_album = baglanti.yap("album");
        myRs_sanatci = baglanti.yap("sanatci");
        myRs_tur = baglanti.yap("tur");
        myRs_s_s = baglanti.yap("sarki_sanatci");
        myRs_a_a = baglanti.yap("album_sanatci");
        myRs_a_s = baglanti.yap("album_sanatci");
        initComponents();
        sarkiguncelle();
        albumguncelle();
        sanatciguncelle();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Sarkılist = new javax.swing.JTable();
        jComboBox_secim = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_sanatci = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable_albumlist = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton_ekle = new javax.swing.JButton();
        jButton_sil = new javax.swing.JButton();
        jButton_duzenle = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1920, 944));

        jTable_Sarkılist.setBackground(new java.awt.Color(153, 153, 153));
        jTable_Sarkılist.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTable_Sarkılist.setForeground(new java.awt.Color(255, 255, 255));
        jTable_Sarkılist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SarkiID", "Şarkı Adı", "Tarih", "Sanatçi", "Albüm", "Tür", "Süre", "Dinlenme"
            }
        ));
        jTable_Sarkılist.setRowHeight(32);
        jScrollPane1.setViewportView(jTable_Sarkılist);

        jComboBox_secim.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jComboBox_secim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sarki", "Sanatci", "Album", " " }));
        jComboBox_secim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_secimActionPerformed(evt);
            }
        });

        jTable_sanatci.setBackground(new java.awt.Color(153, 153, 153));
        jTable_sanatci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sanatçı ID", "Ad", "Ülke"
            }
        ));
        jTable_sanatci.setRowHeight(32);
        jScrollPane2.setViewportView(jTable_sanatci);

        jTable_albumlist.setBackground(new java.awt.Color(153, 153, 153));
        jTable_albumlist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Albüm ID", "Albüm Adı", "Sanatçı", "Tarih", "Tür"
            }
        ));
        jTable_albumlist.setRowHeight(32);
        jScrollPane4.setViewportView(jTable_albumlist);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel3.setBackground(new java.awt.Color(0, 153, 153));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 51, 0));
        jLabel3.setText("ADMIN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jButton_ekle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton_ekle.setText("ekle");
        jButton_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ekleActionPerformed(evt);
            }
        });

        jButton_sil.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton_sil.setText("sil");
        jButton_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_silActionPerformed(evt);
            }
        });

        jButton_duzenle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton_duzenle.setText("düzenle");
        jButton_duzenle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_duzenleActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tüm Albümler");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tüm Şarkılar");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tüm Sanatçılar");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 51));
        jLabel5.setText("MÜZİK KUTUM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 956, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(302, 302, 302)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(221, 221, 221)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(328, 328, 328)
                                .addComponent(jComboBox_secim, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(180, 180, 180)
                                .addComponent(jButton_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(jButton_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jButton_duzenle, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jComboBox_secim, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_sil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_duzenle, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(171, 171, 171))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1594, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_duzenleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_duzenleActionPerformed
            String albm = null,sntci=null;
        if (jComboBox_secim.getSelectedItem().equals("Sarki")) {
            //myRs_s_s = baglanti.ara("select sanatci_id from mzkktm_db.sarki where sarki_id="+jTable1.getValueAt(0,0));
            myRs = baglanti.ara("select album_id,sanatci_id from mzkktm_db.sarki where sarki_id="+jTable1.getValueAt(0, 0) );
            //System.out.println("select album_id,sanatci_id from mzkktm_db.sarki where sarki_id="+jTable1.getValueAt(0, 0));
            try { myRs.next(); 
                //System.out.println(myRs.getInt("album_id"));
                albm = myRs.getString("album_id");
                sntci = myRs.getString("sanatci_id");
                System.out.println("albm: "+albm+" sntci: "+sntci);
                baglanti.guncelle("UPDATE mzkktm_db.album_sarki SET sarki_id='"+jTable1.getValueAt(0, 0)+"',album_id='"+jTable1.getValueAt(0, 4)+"' where sarki_id="+jTable1.getValueAt(0, 0)+" and album_id="+albm  );
            } catch (SQLException ex) {
                Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
            }
            //System.out.println("UPDATE mzkktm_db.album_sarki SET sarki_id='"+jTable1.getValueAt(0, 0)+"',album_id='"+jTable1.getValueAt(0, 4)+"' where sarki_id="+jTable1.getValueAt(0, 0)+" and album_id="+jTable1.getValueAt(0, 4));
            baglanti.guncelle("UPDATE mzkktm_db.sarki_sanatci SET sarki_id='"+jTable1.getValueAt(0, 0)+"',sanatci_id='"+jTable1.getValueAt(0, 3)+"' where sarki_id="+jTable1.getValueAt(0, 0)+" and sanatci_id="+sntci);
            
            baglanti.guncelle("UPDATE mzkktm_db.sarki SET sarki_id='"+jTable1.getValueAt(0, 0)+"',ad='"+jTable1.getValueAt(0, 1)+"'"+",tarih='"+jTable1.getValueAt(0, 2)+"',sanatci_id='"+jTable1.getValueAt(0, 3)+"',album_id='"+jTable1.getValueAt(0, 4)+"',tur_id='"+jTable1.getValueAt(0, 5)+"',sure='"+jTable1.getValueAt(0, 6)+"',dinleme='"+jTable1.getValueAt(0, 7)+"' where sarki_id="+jTable1.getValueAt(0, 0) );
            

            sarkiguncelle();
            albumguncelle();
            sanatciguncelle();
        }
        if (jComboBox_secim.getSelectedItem().equals("Sanatci")) {

            //baglanti.ekle("Insert into mzkktm_db.sanatci(sanatci_id,ad,ulke) VALUES('" + jTable1.getValueAt(0, 0) + "','" + jTable1.getValueAt(0, 1) + "','" + jTable1.getValueAt(0, 2) + "')");
            baglanti.guncelle("UPDATE mzkktm_db.sanatci SET ad='"+jTable1.getValueAt(0, 1)+"',ulke='"+jTable1.getValueAt(0, 2)+"' where sanatci_id="+jTable1.getValueAt(0, 0) );

            sarkiguncelle();
            albumguncelle();
            sanatciguncelle();
        }
        if (jComboBox_secim.getSelectedItem().equals("Album")) {
            //baglanti.ekle("Insert into mzkktm_db.album(album_id,ad,tarih,tur_id) VALUES('" + jTable1.getValueAt(0, 0) + "','" + jTable1.getValueAt(0, 1) + "','" + jTable1.getValueAt(0, 2) + "','" + jTable1.getValueAt(0, 3) + "')");
            baglanti.guncelle("UPDATE mzkktm_db.album SET ad='"+jTable1.getValueAt(0, 1)+"',tarih='"+jTable1.getValueAt(0, 2)+"',tur_id='"+jTable1.getValueAt(0, 3)+"' where album_id="+jTable1.getValueAt(0, 0) );
            
            baglanti.guncelle("UPDATE mzkktm_db.sarki SET tarih='"+jTable1.getValueAt(0, 2)+"' where album_id="+jTable1.getValueAt(0, 0) );
            myRs_a_a = baglanti.ara("SELECT sanatci_id FROM mzkktm_db.album_sanatci where album_id="+jTable1.getValueAt(0, 0));
                try { myRs_a_a.next();
                    //System.out.println(""+myRs_a_a.getString("sanatci_id"));
                baglanti.guncelle("UPDATE mzkktm_db.sanatci SET ad='"+jTable1.getValueAt(0, 4)+"' where sanatci_id="+myRs_a_a.getString("sanatci_id") );
                   
                } catch (SQLException ex) {
                    Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
                }
            //baglanti.ekle("Insert into mzkktm_db.album_sanatci(album_id,sanatci_id) VALUES('"+jTable1.getValueAt(0,0)+"','"+jTable1.getValueAt(0,4)+"')");

            sarkiguncelle();
            albumguncelle();
            sanatciguncelle();
        }
    }//GEN-LAST:event_jButton_duzenleActionPerformed

    private void jButton_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_silActionPerformed
        if (jComboBox_secim.getSelectedItem().equals("Sarki")) {

            //baglanti.ekle("Insert into mzkktm_db.sarki(sarki_id,ad,tarih,sanatci_id,album_id,tur_id,sure,dinleme) VALUES('" + jTable1.getValueAt(0, 0) + "','"
                //       + jTable1.getValueAt(0, 1) + "','" + jTable1.getValueAt(0, 2) + "','" + jTable1.getValueAt(0, 3) + "','" + jTable1.getValueAt(0, 4) + "','" + jTable1.getValueAt(0, 5) + "','"
                //       + jTable1.getValueAt(0, 6) + "','" + jTable1.getValueAt(0, 7) + "')");
            try {
                baglanti.sil("DELETE from mzkktm_db.sarki where sarki_id="+jTable1.getValueAt(0, 0) );
            } catch (SQLException ex) {
                Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
            }
            //baglanti.ekle("Insert into mzkktm_db.sarkı_sanatci(sarki_id,sanatci_id) VALUES('" + jTable1.getValueAt(0, 0) + "','" + jTable1.getValueAt(0, 3) + "')");
            //baglanti.ekle("Insert into mzkktm_db.album_sarki(sarki_id,album_id) VALUES('" + jTable1.getValueAt(0, 0) + "','" + jTable1.getValueAt(0, 4) + "')");

            sarkiguncelle();
        }
        if (jComboBox_secim.getSelectedItem().equals("Sanatci")) {
            try { 
                //baglanti.ekle("Insert into mzkktm_db.sanatci(sanatci_id,ad,ulke) VALUES('" + jTable1.getValueAt(0, 0) + "','" + jTable1.getValueAt(0, 1) + "','" + jTable1.getValueAt(0, 2) + "')");
                baglanti.sil("DELETE s.* from mzkktm_db.sarki as s, mzkktm_db.sarki_sanatci as s_s where s_s.sanatci_id="+jTable1.getValueAt(0, 0)+" and s.sarki_id=s_s.sarki_id");
                baglanti.sil("DELETE a.* from mzkktm_db.album as a , mzkktm_db.album_sanatci as a_s where a_s.sanatci_id="+jTable1.getValueAt(0, 0)+" and a.album_id=a_s.album_id");
                baglanti.sil("DELETE from mzkktm_db.sanatci where sanatci_id="+jTable1.getValueAt(0, 0) );
                //myRs_a_s = baglanti.ara(" select album_id from mzkktm_db.album_sanatci where sanatci_id="+jTable1.getValueAt(0, 0));
                
                
            } catch (SQLException ex) {
                Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
            }
            sanatciguncelle();
            albumguncelle();
            sarkiguncelle();
        }
        if (jComboBox_secim.getSelectedItem().equals("Album")) {
            try {
                // baglanti.ekle("Insert into mzkktm_db.album(album_id,ad,tarih,tur_id) VALUES('" + jTable1.getValueAt(0, 0) + "','" + jTable1.getValueAt(0, 1) + "','" + jTable1.getValueAt(0, 2) + "','" + jTable1.getValueAt(0, 3) + "')");
                //baglanti.ekle("Insert into mzkktm_db.album_sanatci(album_id,sanatci_id) VALUES('"+jTable1.getValueAt(0,0)+"','"+jTable1.getValueAt(0,4)+"')");
                baglanti.sil("DELETE from mzkktm_db.album where album_id="+jTable1.getValueAt(0, 0) );
                baglanti.sil("DELETE from mzkktm_db.sarki where album_id="+jTable1.getValueAt(0, 0) );
                
            } catch (SQLException ex) {
                Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
            }
            albumguncelle();
            sarkiguncelle();
        }
    }//GEN-LAST:event_jButton_silActionPerformed

    private void jButton_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ekleActionPerformed

        if (jComboBox_secim.getSelectedItem().equals("Sarki")) {

            baglanti.ekle("Insert into mzkktm_db.sarki(sarki_id,ad,tarih,sanatci_id,album_id,tur_id,sure,dinleme) VALUES('" + jTable1.getValueAt(0, 0) + "','"
                + jTable1.getValueAt(0, 1) + "','" + jTable1.getValueAt(0, 2) + "','" + jTable1.getValueAt(0, 3) + "','" + jTable1.getValueAt(0, 4) + "','" + jTable1.getValueAt(0, 5) + "','"
                + jTable1.getValueAt(0, 6) + "','" + jTable1.getValueAt(0, 7) + "')");
            baglanti.ekle("Insert into mzkktm_db.sarkı_sanatci(sarki_id,sanatci_id) VALUES('" + jTable1.getValueAt(0, 0) + "','" + jTable1.getValueAt(0, 3) + "')");
            baglanti.ekle("Insert into mzkktm_db.album_sarki(sarki_id,album_id) VALUES('" + jTable1.getValueAt(0, 0) + "','" + jTable1.getValueAt(0, 4) + "')");

            sarkiguncelle();
        }
        if (jComboBox_secim.getSelectedItem().equals("Sanatci")) {

            baglanti.ekle("Insert into mzkktm_db.sanatci(sanatci_id,ad,ulke) VALUES('" + jTable1.getValueAt(0, 0) + "','" + jTable1.getValueAt(0, 1) + "','" + jTable1.getValueAt(0, 2) + "')");

            sanatciguncelle();
        }
        if (jComboBox_secim.getSelectedItem().equals("Album")) {
            baglanti.ekle("Insert into mzkktm_db.album(album_id,ad,tarih,tur_id) VALUES('" + jTable1.getValueAt(0, 0) + "','" + jTable1.getValueAt(0, 1) + "','" + jTable1.getValueAt(0, 2) + "','" + jTable1.getValueAt(0, 3) + "')");
            baglanti.ekle("Insert into mzkktm_db.album_sanatci(album_id,sanatci_id) VALUES('"+jTable1.getValueAt(0,0)+"','"+jTable1.getValueAt(0,4)+"')");
            albumguncelle();
        }
    }//GEN-LAST:event_jButton_ekleActionPerformed

    private void jComboBox_secimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_secimActionPerformed

        if (jComboBox_secim.getSelectedItem().equals("Sarki")) {
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setColumnCount(0);
            dtm.addColumn("SarkıID");
            dtm.addColumn("Ad");
            dtm.addColumn("Tarih");
            dtm.addColumn("Sanatci_id");
            dtm.addColumn("Album_id");
            dtm.addColumn("Tur_id");
            dtm.addColumn("Sure");
            dtm.addColumn("Dinlenme");

        }
        if (jComboBox_secim.getSelectedItem().equals("Sanatci")) {
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setColumnCount(0);
            dtm.addColumn("SanatciID");
            dtm.addColumn("Ad");
            dtm.addColumn("Ulke");
        }
        if (jComboBox_secim.getSelectedItem().equals("Album")) {

            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setColumnCount(0);
            dtm.addColumn("AlbumID");
            dtm.addColumn("Ad");
            dtm.addColumn("Tarih");
            dtm.addColumn("TurID");
            dtm.addColumn("Sanatci");
        }
    }//GEN-LAST:event_jComboBox_secimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Admin().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_duzenle;
    private javax.swing.JButton jButton_ekle;
    private javax.swing.JButton jButton_sil;
    private javax.swing.JComboBox<String> jComboBox_secim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable_Sarkılist;
    private javax.swing.JTable jTable_albumlist;
    private javax.swing.JTable jTable_sanatci;
    // End of variables declaration//GEN-END:variables

    public void sarkiguncelle() {

        myRs = baglanti.ara("select distinct s.*,a.ad,sanatci.ad,tur.ad from mzkktm_db.sarki as s, mzkktm_db.album as a , mzkktm_db.sanatci,mzkktm_db.tur where s.album_id=a.album_id and s.sanatci_id=sanatci.sanatci_id and tur.tur_id=s.tur_id ORDER BY sarki_id");
        try {
            model = (DefaultTableModel) jTable_Sarkılist.getModel();
            if (model.getRowCount() != 0) {
                model.setRowCount(0);
            }
            while (myRs.next()) {

                model.addRow(new Object[]{myRs.getInt(1), myRs.getString(2), myRs.getString(3), myRs.getString("sanatci.ad"), myRs.getString("a.ad"), myRs.getString("tur.ad"), myRs.getString(7), myRs.getString(8)});

            }
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void albumguncelle() {

        myRs_album = baglanti.ara("select distinct a.*,s.ad from mzkktm_db.album as a,mzkktm_db.sanatci as s ,mzkktm_db.album_sanatci as a_s where a.album_id=a_s.album_id and a_s.sanatci_id=s.sanatci_id ");
        try {
            model = (DefaultTableModel) jTable_albumlist.getModel();
            if (model.getRowCount() != 0) {
                model.setRowCount(0);
            }
            while (myRs_album.next()) {

                model.addRow(new Object[]{myRs_album.getInt(1), myRs_album.getString(2), myRs_album.getString("s.ad"), myRs_album.getString(3), myRs_album.getString(4)});
            }
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void sanatciguncelle() {

        myRs_sanatci = baglanti.ara("select s.* from mzkktm_db.sanatci as s");
        try {
            model = (DefaultTableModel) jTable_sanatci.getModel();
            if (model.getRowCount() != 0) {
                model.setRowCount(0);
            }
            while (myRs_sanatci.next()) {

                model.addRow(new Object[]{myRs_sanatci.getInt(1), myRs_sanatci.getString(2), myRs_sanatci.getString(3)});
            }
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

}
