
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import com.mysql.cj.protocol.Resultset;
import java.sql.Statement;
import java.sql.Connection;

import java.net.ConnectException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

public class kullanici extends javax.swing.JFrame {
    
    
    Baglanti baglanti = new Baglanti();
    ResultSet myRs = null;
    ResultSet myRs_sanatci = null;
    ResultSet myRs_k_s = null;
    ResultSet myRs_album = null;
    ResultSet myRs_tur = null;
    ResultSet myRs_K = null;
    ResultSet myRs_Kk = null;
    ResultSet myRs_C = null;
    DefaultTableModel model;
    int CalmaListesiAdedi =1;
    public kullanici() throws SQLException {
        initComponents();
        
        login l = new login();
        int kullanici_id = l.kullanici_id;
        
        myRs = baglanti.yap("sarki");
        myRs_k_s = baglanti.yap("kullanici_sarki");
        myRs_album = baglanti.yap("album");
        myRs_sanatci = baglanti.yap("sanatci");
        myRs_tur = baglanti.yap("tur");

        myRs = baglanti.ara("select distinct s.*,a.ad,sanatci.ad,tur.ad from mzkktm_db.sarki as s,mzkktm_db.kullanici_sarki as k_s , mzkktm_db.album as a , mzkktm_db.sanatci,mzkktm_db.tur where    k_s.kullanici_id=" + kullanici_id + " and s.sarki_id=k_s.sarki_id and s.album_id=a.album_id and s.sanatci_id=sanatci.sanatci_id and tur.tur_id=s.tur_id");

        while (myRs.next()) {

            model = (DefaultTableModel) jTable_Sarkılist.getModel();

            model.addRow(new Object[]{myRs.getInt(1), myRs.getString(2), myRs.getString(3), myRs.getString("sanatci.ad"), myRs.getString("a.ad"), myRs.getString("tur.ad"), myRs.getString(7), myRs.getString(8)});

        }
        myRs_K = baglanti.ara("select * from mzkktm_db.kullanici");
        DefaultListModel dm = new DefaultListModel();
        users.setModel(dm);
        while (myRs_K.next()) {
            if (myRs_K.getInt("abonlik_id") == 2) {
                dm.addElement(myRs_K.getString("kullanici_id") + " " + myRs_K.getString("ad"));
            }

        }
        myRs_Kk = baglanti.ara("select k.ad from mzkktm_db.kullanici_kullanici as kk, mzkktm_db.kullanici k where kk.takipedilenkullanici_id=k.kullanici_id and kk.anakullanici_id=" + l.kullanici_id);
        DefaultListModel d = new DefaultListModel();
        frndlst.setModel(d);
        while (myRs_Kk.next()) {

            d.addElement(myRs_Kk.getString("k.ad"));

        }
//        myRs = baglanti.ara("select liste_id from mzkktm_db.calmalistesi where kullanici_id="+l.kullanici_id);
//        while(myRs.next()){
//            System.out.println("a"+myRs.getInt(1));
//            if(myRs.getInt(1)!=0){
//                DefaultComboBoxModel model = (DefaultComboBoxModel) CalmaListem.getModel();
//                CalmaListem.addItem("Calma Listesi "+myRs.getInt(1));
//                System.out.println("b"+myRs.getInt(1));
//                //CalmaListesiAdedi = myRs.getInt(1);
//                
//            }
//            
//        } 
//        //CalmaListesiAdedi++;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton_Home = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton_My_Jazz = new javax.swing.JButton();
        jButton_Mp_Pop = new javax.swing.JButton();
        jButton_My_Klasik = new javax.swing.JButton();
        calma_buton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        frndlst = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        users = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton_tp_Jazz = new javax.swing.JButton();
        jButton_tp_Pop = new javax.swing.JButton();
        jButton_tp_Klasik = new javax.swing.JButton();
        jButton_tp_Peru = new javax.swing.JButton();
        jButton_tp_Turkey = new javax.swing.JButton();
        jButton_tp_Usa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Sarkılist = new javax.swing.JTable();
        jLabel_SarkiLİST = new javax.swing.JLabel();
        jButton_sarkiekle = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField_SarkıId = new javax.swing.JTextField();
        jButton_llisteekle = new javax.swing.JButton();
        SarkiEkle2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jButton_Home.setBackground(new java.awt.Color(102, 102, 102));
        jButton_Home.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton_Home.setText("Home");
        jButton_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_HomeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MY LİST ");

        jButton_My_Jazz.setBackground(new java.awt.Color(102, 102, 102));
        jButton_My_Jazz.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton_My_Jazz.setText("JAZZ");
        jButton_My_Jazz.setMaximumSize(new java.awt.Dimension(65, 21));
        jButton_My_Jazz.setMinimumSize(new java.awt.Dimension(65, 21));
        jButton_My_Jazz.setPreferredSize(new java.awt.Dimension(65, 21));
        jButton_My_Jazz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_My_JazzActionPerformed(evt);
            }
        });

        jButton_Mp_Pop.setBackground(new java.awt.Color(102, 102, 102));
        jButton_Mp_Pop.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton_Mp_Pop.setText("POP");
        jButton_Mp_Pop.setMaximumSize(new java.awt.Dimension(65, 21));
        jButton_Mp_Pop.setMinimumSize(new java.awt.Dimension(65, 21));
        jButton_Mp_Pop.setPreferredSize(new java.awt.Dimension(65, 21));
        jButton_Mp_Pop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Mp_PopActionPerformed(evt);
            }
        });

        jButton_My_Klasik.setBackground(new java.awt.Color(102, 102, 102));
        jButton_My_Klasik.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton_My_Klasik.setText("KLASİK");
        jButton_My_Klasik.setMaximumSize(new java.awt.Dimension(65, 21));
        jButton_My_Klasik.setMinimumSize(new java.awt.Dimension(65, 21));
        jButton_My_Klasik.setPreferredSize(new java.awt.Dimension(65, 21));
        jButton_My_Klasik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_My_KlasikActionPerformed(evt);
            }
        });

        calma_buton.setText("Çalma Listem");
        calma_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calma_butonActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton2.setText("Tüm Şarkılar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(calma_buton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_My_Jazz, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(jButton_Mp_Pop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(jButton_My_Klasik, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))))
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addComponent(jButton_My_Jazz, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton_Mp_Pop, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton_My_Klasik, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(calma_buton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("KULLANICILAR ");

        frndlst.setBackground(new java.awt.Color(102, 102, 102));
        frndlst.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        frndlst.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "ali", "ahmet", "mehmet", "veli", "halil", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(frndlst);

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Takip ettiklerim ");

        users.setBackground(new java.awt.Color(102, 102, 102));
        users.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        users.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "ali", "ahmet", "mehmet", "veli", "halil", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(users);

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton1.setText("takip et");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(jLabel8)
                    .addContainerGap(45, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(691, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jButton_tp_Jazz.setBackground(new java.awt.Color(102, 102, 102));
        jButton_tp_Jazz.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton_tp_Jazz.setText("JAZZ");
        jButton_tp_Jazz.setMaximumSize(new java.awt.Dimension(65, 21));
        jButton_tp_Jazz.setMinimumSize(new java.awt.Dimension(65, 21));
        jButton_tp_Jazz.setPreferredSize(new java.awt.Dimension(65, 21));
        jButton_tp_Jazz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_tp_JazzActionPerformed(evt);
            }
        });

        jButton_tp_Pop.setBackground(new java.awt.Color(102, 102, 102));
        jButton_tp_Pop.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton_tp_Pop.setText("POP");
        jButton_tp_Pop.setMaximumSize(new java.awt.Dimension(65, 21));
        jButton_tp_Pop.setMinimumSize(new java.awt.Dimension(65, 21));
        jButton_tp_Pop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_tp_PopActionPerformed(evt);
            }
        });

        jButton_tp_Klasik.setBackground(new java.awt.Color(102, 102, 102));
        jButton_tp_Klasik.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton_tp_Klasik.setText("KLASİK");
        jButton_tp_Klasik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_tp_KlasikActionPerformed(evt);
            }
        });

        jButton_tp_Peru.setBackground(new java.awt.Color(102, 102, 102));
        jButton_tp_Peru.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton_tp_Peru.setText("PERU");
        jButton_tp_Peru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_tp_PeruActionPerformed(evt);
            }
        });

        jButton_tp_Turkey.setBackground(new java.awt.Color(102, 102, 102));
        jButton_tp_Turkey.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton_tp_Turkey.setText("TURKEY");
        jButton_tp_Turkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_tp_TurkeyActionPerformed(evt);
            }
        });

        jButton_tp_Usa.setBackground(new java.awt.Color(102, 102, 102));
        jButton_tp_Usa.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton_tp_Usa.setText("USA");
        jButton_tp_Usa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_tp_UsaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TOP 10 ");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 51));
        jLabel3.setText("MÜZİK KUTUM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jButton_tp_Jazz, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_tp_Pop, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_tp_Klasik, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_tp_Peru)
                        .addGap(31, 31, 31)))
                .addComponent(jButton_tp_Turkey)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_tp_Usa, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_tp_Peru, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_tp_Turkey, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_tp_Usa, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_tp_Klasik, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_tp_Pop, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_tp_Jazz, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setToolTipText("");

        jTable_Sarkılist.setBackground(new java.awt.Color(153, 153, 153));
        jTable_Sarkılist.setForeground(new java.awt.Color(255, 255, 255));
        jTable_Sarkılist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SarkiID", "Şarkı Adı", "Tarih", "Sanatçi", "Albüm", "Tür", "Süre", "Dinlenme"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Sarkılist.setRowHeight(32);
        jScrollPane1.setViewportView(jTable_Sarkılist);

        jLabel_SarkiLİST.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel_SarkiLİST.setText("LİST ");

        jButton_sarkiekle.setBackground(new java.awt.Color(102, 102, 102));
        jButton_sarkiekle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton_sarkiekle.setText("EKLE");
        jButton_sarkiekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sarkiekleActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel9.setText("ŞARKI EKlE ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel10.setText("Listeye Şarkı Ekle");

        jTextField_SarkıId.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField_SarkıId.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_SarkıId.setText("SARKIID");
        jTextField_SarkıId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_SarkıIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_SarkıIdFocusLost(evt);
            }
        });
        jTextField_SarkıId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_SarkıIdActionPerformed(evt);
            }
        });

        jButton_llisteekle.setBackground(new java.awt.Color(102, 102, 102));
        jButton_llisteekle.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton_llisteekle.setText("EKLE");
        jButton_llisteekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_llisteekleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(501, 501, 501)
                .addComponent(jLabel_SarkiLİST, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1078, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(SarkiEkle2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButton_llisteekle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(622, 622, 622)
                        .addComponent(jTextField_SarkıId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jButton_sarkiekle)))
                .addGap(191, 191, 191))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel_SarkiLİST, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SarkiEkle2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_llisteekle, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_SarkıId, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_sarkiekle))))
                .addGap(116, 116, 116))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1131, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_SarkıIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_SarkıIdFocusLost
        if (jTextField_SarkıId.getText().trim().toLowerCase().equals("")
                || jTextField_SarkıId.getText().trim().toLowerCase().equals("sarkııd")) {

            jTextField_SarkıId.setText("SarkıID");
            jTextField_SarkıId.setForeground(new Color(153, 153, 153));

        }
    }//GEN-LAST:event_jTextField_SarkıIdFocusLost

    private void jTextField_SarkıIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_SarkıIdFocusGained
        if (jTextField_SarkıId.getText().trim().toLowerCase().equals("sarkııd")) {
            jTextField_SarkıId.setText("");
            jTextField_SarkıId.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_SarkıIdFocusGained

    private void jButton_tp_JazzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_tp_JazzActionPerformed
        login l = new login();
        if(model!=null){
           model.setRowCount(0); 
        }
        int i = 0;
        myRs = baglanti.ara("select s.*,a.ad,sanatci.ad,tur.ad from mzkktm_db.sarki as s, mzkktm_db.album as a , mzkktm_db.sanatci,mzkktm_db.tur where s.album_id=a.album_id and s.sanatci_id=sanatci.sanatci_id and tur.tur_id=s.tur_id and tur.ad='jazz' ORDER BY dinleme");
        try {
            while (i < 10 & myRs.next()) {

                model = (DefaultTableModel) jTable_Sarkılist.getModel();

                model.addRow(new Object[]{myRs.getInt(1), myRs.getString(2), myRs.getString(3), myRs.getString("sanatci.ad"), myRs.getString("a.ad"), myRs.getString("tur.ad"), myRs.getString(7), myRs.getString(8)});
                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(kullanici.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_tp_JazzActionPerformed

    private void jButton_tp_PopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_tp_PopActionPerformed
        login l = new login();
        if(model!=null){
           model.setRowCount(0); 
        }
        int i = 0;
        myRs = baglanti.ara("select s.*,a.ad,sanatci.ad,tur.ad from mzkktm_db.sarki as s, mzkktm_db.album as a , mzkktm_db.sanatci,mzkktm_db.tur where s.album_id=a.album_id and s.sanatci_id=sanatci.sanatci_id and tur.tur_id=s.tur_id and tur.ad='Pop' ORDER BY dinleme desc");
        try {
            while (i < 10 & myRs.next()) {

                model = (DefaultTableModel) jTable_Sarkılist.getModel();

                model.addRow(new Object[]{myRs.getInt(1), myRs.getString(2), myRs.getString(3), myRs.getString("sanatci.ad"), myRs.getString("a.ad"), myRs.getString("tur.ad"), myRs.getString(7), myRs.getString(8)});
                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(kullanici.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_tp_PopActionPerformed

    private void jButton_tp_KlasikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_tp_KlasikActionPerformed
        login l = new login();
        if(model!=null){
           model.setRowCount(0); 
        }
        int i = 0;
        myRs = baglanti.ara("select s.*,a.ad,sanatci.ad,tur.ad from mzkktm_db.sarki as s, mzkktm_db.album as a , mzkktm_db.sanatci,mzkktm_db.tur where s.album_id=a.album_id and s.sanatci_id=sanatci.sanatci_id and tur.tur_id=s.tur_id and tur.ad='klasik' ORDER BY dinleme desc");
        try {
            while (i < 10 & myRs.next()) {

                model = (DefaultTableModel) jTable_Sarkılist.getModel();

                model.addRow(new Object[]{myRs.getInt(1), myRs.getString(2), myRs.getString(3), myRs.getString("sanatci.ad"), myRs.getString("a.ad"), myRs.getString("tur.ad"), myRs.getString(7), myRs.getString(8)});
                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(kullanici.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_tp_KlasikActionPerformed

    private void jButton_tp_PeruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_tp_PeruActionPerformed
        login l = new login();
        if(model!=null){
           model.setRowCount(0); 
        }
        int i = 0;
        myRs = baglanti.ara("select s.*,a.ad,sanatci.ad,tur.ad from mzkktm_db.sarki as s, mzkktm_db.album as a , mzkktm_db.sanatci,mzkktm_db.tur where s.album_id=a.album_id and s.sanatci_id=sanatci.sanatci_id and tur.tur_id=s.tur_id and sanatci.ulke='peru' ORDER BY dinleme desc");

        try {
            while (i < 10 & myRs.next()) {

                model = (DefaultTableModel) jTable_Sarkılist.getModel();

                model.addRow(new Object[]{myRs.getInt(1), myRs.getString(2), myRs.getString(3), myRs.getString("sanatci.ad"), myRs.getString("a.ad"), myRs.getString("tur.ad"), myRs.getString(7), myRs.getString(8)});
                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(kullanici.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_tp_PeruActionPerformed

    private void jButton_tp_TurkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_tp_TurkeyActionPerformed
        login l = new login();
        if(model!=null){
           model.setRowCount(0); 
        }
        int i = 0;
        myRs = baglanti.ara("select s.*,a.ad,sanatci.ad,tur.ad from mzkktm_db.sarki as s, mzkktm_db.album as a , mzkktm_db.sanatci,mzkktm_db.tur where s.album_id=a.album_id and s.sanatci_id=sanatci.sanatci_id and tur.tur_id=s.tur_id and sanatci.ulke='turkey' ORDER BY dinleme desc");
        try {
            while (i < 10 & myRs.next()) {

                model = (DefaultTableModel) jTable_Sarkılist.getModel();

                model.addRow(new Object[]{myRs.getInt(1), myRs.getString(2), myRs.getString(3), myRs.getString("sanatci.ad"), myRs.getString("a.ad"), myRs.getString("tur.ad"), myRs.getString(7), myRs.getString(8)});
                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(kullanici.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_tp_TurkeyActionPerformed

    private void jButton_tp_UsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_tp_UsaActionPerformed
        login l = new login();
        if(model!=null){
           model.setRowCount(0); 
        }
        int i = 0;
        myRs = baglanti.ara("select s.*,a.ad,sanatci.ad,tur.ad from mzkktm_db.sarki as s, mzkktm_db.album as a , mzkktm_db.sanatci,mzkktm_db.tur where s.album_id=a.album_id and s.sanatci_id=sanatci.sanatci_id and tur.tur_id=s.tur_id and sanatci.ulke='usa' ORDER BY dinleme desc");
        try {
            while (i < 10 & myRs.next()) {

                model = (DefaultTableModel) jTable_Sarkılist.getModel();

                model.addRow(new Object[]{myRs.getInt(1), myRs.getString(2), myRs.getString(3), myRs.getString("sanatci.ad"), myRs.getString("a.ad"), myRs.getString("tur.ad"), myRs.getString(7), myRs.getString(8)});
                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(kullanici.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_tp_UsaActionPerformed

    private void jButton_sarkiekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sarkiekleActionPerformed
        login l = new login();
        baglanti.ekle("Insert into mzkktm_db.kullanici_sarki(kullanici_id,sarki_id,liste_tur) VALUES('" + l.kullanici_id + "','" + jTextField_SarkıId.getText() + "','" + 1 + "')");

    }//GEN-LAST:event_jButton_sarkiekleActionPerformed

    private void jButton_My_KlasikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_My_KlasikActionPerformed
        login l = new login();
        model.setRowCount(0);
        myRs = baglanti.ara("select s.*,a.ad,sanatci.ad,tur.ad from mzkktm_db.sarki as s,mzkktm_db.kullanici_sarki as k_s , mzkktm_db.album as a , mzkktm_db.sanatci,mzkktm_db.tur where    k_s.kullanici_id=" + l.kullanici_id + " and s.sarki_id=k_s.sarki_id and s.album_id=a.album_id and s.sanatci_id=sanatci.sanatci_id and tur.tur_id=s.tur_id and tur.ad='klasik' and k_s.liste_tur=1");
        try {
            while (myRs.next()) {

                model = (DefaultTableModel) jTable_Sarkılist.getModel();

                model.addRow(new Object[]{myRs.getInt(1), myRs.getString(2), myRs.getString(3), myRs.getString("sanatci.ad"), myRs.getString("a.ad"), myRs.getString("tur.ad"), myRs.getString(7), myRs.getString(8)});

            }
        } catch (SQLException ex) {
            Logger.getLogger(kullanici.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_My_KlasikActionPerformed

    private void jButton_Mp_PopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Mp_PopActionPerformed
        login l = new login();
        model.setRowCount(0);
        myRs = baglanti.ara("select s.*,a.ad,sanatci.ad,tur.ad from mzkktm_db.sarki as s,mzkktm_db.kullanici_sarki as k_s , mzkktm_db.album as a , mzkktm_db.sanatci,mzkktm_db.tur where    k_s.kullanici_id=" + l.kullanici_id + " and s.sarki_id=k_s.sarki_id and s.album_id=a.album_id and s.sanatci_id=sanatci.sanatci_id and tur.tur_id=s.tur_id and tur.ad='pop' and k_s.liste_tur=1");
        try {
            while (myRs.next()) {

                model = (DefaultTableModel) jTable_Sarkılist.getModel();

                model.addRow(new Object[]{myRs.getInt(1), myRs.getString(2), myRs.getString(3), myRs.getString("sanatci.ad"), myRs.getString("a.ad"), myRs.getString("tur.ad"), myRs.getString(7), myRs.getString(8)});

            }
        } catch (SQLException ex) {
            Logger.getLogger(kullanici.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_Mp_PopActionPerformed

    private void jButton_My_JazzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_My_JazzActionPerformed
        login l = new login();
        model.setRowCount(0);
        myRs = baglanti.ara("select s.*,a.ad,sanatci.ad,tur.ad from mzkktm_db.sarki as s,mzkktm_db.kullanici_sarki as k_s , mzkktm_db.album as a , mzkktm_db.sanatci,mzkktm_db.tur where    k_s.kullanici_id=" + l.kullanici_id + " and s.sarki_id=k_s.sarki_id and s.album_id=a.album_id and s.sanatci_id=sanatci.sanatci_id and tur.tur_id=s.tur_id and tur.ad='jazz' and k_s.liste_tur=1");
        try {
            while (myRs.next()) {

                model = (DefaultTableModel) jTable_Sarkılist.getModel();

                model.addRow(new Object[]{myRs.getInt(1), myRs.getString(2), myRs.getString(3), myRs.getString("sanatci.ad"), myRs.getString("a.ad"), myRs.getString("tur.ad"), myRs.getString(7), myRs.getString(8)});

            }
        } catch (SQLException ex) {
            Logger.getLogger(kullanici.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_My_JazzActionPerformed

    private void jButton_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_HomeActionPerformed
        login l = new login();
        model.setRowCount(0);
        myRs = baglanti.ara("select distinct s.sarki_id, s.*,a.ad,sanatci.ad,tur.ad from mzkktm_db.sarki as s,mzkktm_db.kullanici_sarki as k_s , mzkktm_db.album as a , mzkktm_db.sanatci,mzkktm_db.tur where    k_s.kullanici_id=" + l.kullanici_id + " and s.sarki_id=k_s.sarki_id and s.album_id=a.album_id and s.sanatci_id=sanatci.sanatci_id and tur.tur_id=s.tur_id");
        try {
            while (myRs.next()) {

                model = (DefaultTableModel) jTable_Sarkılist.getModel();

                model.addRow(new Object[]{myRs.getInt(1), myRs.getString(3), myRs.getString(4), myRs.getString("sanatci.ad"), myRs.getString("a.ad"), myRs.getString("tur.ad"), myRs.getString(8), myRs.getString(9)});

            }
        } catch (SQLException ex) {
            Logger.getLogger(kullanici.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_HomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        login l = new login();
        baglanti.ekle("Insert into mzkktm_db.kullanici_kullanici(anakullanici_id,takipedilenkullanici_id) VALUES('" + l.kullanici_id + "','" + users.getSelectedValue().toString().charAt(0) + "')");
        myRs_Kk = baglanti.ara("select k.ad from mzkktm_db.kullanici_kullanici as kk, mzkktm_db.kullanici k where kk.takipedilenkullanici_id=k.kullanici_id and kk.anakullanici_id=" + l.kullanici_id);
        DefaultListModel d = new DefaultListModel();
        frndlst.setModel(d);
        try {
            model.setRowCount(0);
            while (myRs_Kk.next()) {

                d.addElement(myRs_Kk.getString("k.ad"));

            }
        } catch (SQLException ex) {
            Logger.getLogger(kullanici.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void usersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersMouseClicked

        myRs = baglanti.ara("select s.*,a.ad,sanatci.ad,tur.ad from mzkktm_db.sarki as s,mzkktm_db.kullanici_sarki as k_s , mzkktm_db.album as a , mzkktm_db.sanatci,mzkktm_db.tur where    k_s.kullanici_id=" + users.getSelectedValue().toString().charAt(0) + " and s.sarki_id=k_s.sarki_id and s.album_id=a.album_id and s.sanatci_id=sanatci.sanatci_id and tur.tur_id=s.tur_id");
        try {

            if(model!=null){
           model.setRowCount(0); 
        }

            while (myRs.next()) {

                model = (DefaultTableModel) jTable_Sarkılist.getModel();

                model.addRow(new Object[]{myRs.getInt(1), myRs.getString(2), myRs.getString(3), myRs.getString("sanatci.ad"), myRs.getString("a.ad"), myRs.getString("tur.ad"), myRs.getString(7), myRs.getString(8)});

            }
        } catch (SQLException ex) {
            Logger.getLogger(kullanici.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_usersMouseClicked

    private void jButton_llisteekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_llisteekleActionPerformed
        login l = new login();
        baglanti.ekle("Insert into mzkktm_db.kullanici_sarki(kullanici_id,sarki_id,liste_tur) VALUES('" + l.kullanici_id + "','" + SarkiEkle2.getText() + "','" + 2 + "')");
//        DefaultComboBoxModel model = (DefaultComboBoxModel) CalmaListem.getModel();
//        CalmaListem.addItem("Calma Listesi "+CalmaListesiAdedi);
//        baglanti.ekle("insert into mzkktm_db.calmalistesi(kullanici_id,liste_id) VALUES ('"+l.kullanici_id+"','"+CalmaListesiAdedi+"')");
//        
//        CalmaListesiAdedi++;
    }//GEN-LAST:event_jButton_llisteekleActionPerformed

    private void calma_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calma_butonActionPerformed
        login l = new login();
        model.setRowCount(0);
        myRs = baglanti.ara("select s.*,a.ad,sanatci.ad,tur.ad from mzkktm_db.sarki as s,mzkktm_db.kullanici_sarki as k_s , mzkktm_db.album as a , mzkktm_db.sanatci,mzkktm_db.tur where    k_s.kullanici_id=" + l.kullanici_id + " and s.sarki_id=k_s.sarki_id and s.album_id=a.album_id and s.sanatci_id=sanatci.sanatci_id and tur.tur_id=s.tur_id and k_s.liste_tur="+2);
        try {
            while (myRs.next()) {

                model = (DefaultTableModel) jTable_Sarkılist.getModel();

                model.addRow(new Object[]{myRs.getInt(1), myRs.getString(2), myRs.getString(3), myRs.getString("sanatci.ad"), myRs.getString("a.ad"), myRs.getString("tur.ad"), myRs.getString(7), myRs.getString(8)});

            }
        } catch (SQLException ex) {
            Logger.getLogger(kullanici.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_calma_butonActionPerformed

    private void jTextField_SarkıIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_SarkıIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_SarkıIdActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        login l = new login();
        if(model!=null){
           model.setRowCount(0); 
        }
        System.out.println("basildi");
        myRs = baglanti.ara("select distinct s.sarki_id, s.*,a.ad,sanatci.ad,tur.ad from mzkktm_db.sarki as s , mzkktm_db.album as a , mzkktm_db.sanatci,mzkktm_db.tur where s.album_id=a.album_id and s.sanatci_id=sanatci.sanatci_id and tur.tur_id=s.tur_id ORDER BY s.sarki_id asc");
        try {
            while (myRs.next()) {

                model = (DefaultTableModel) jTable_Sarkılist.getModel();

                model.addRow(new Object[]{myRs.getInt(1), myRs.getString(3), myRs.getString(4), myRs.getString("sanatci.ad"), myRs.getString("a.ad"), myRs.getString("tur.ad"), myRs.getString(8), myRs.getString(9)});

            }
        } catch (SQLException ex) {
            Logger.getLogger(kullanici.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kullanici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kullanici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kullanici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kullanici.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new kullanici().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(kullanici.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SarkiEkle2;
    private javax.swing.JButton calma_buton;
    private javax.swing.JList<String> frndlst;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_Home;
    private javax.swing.JButton jButton_Mp_Pop;
    private javax.swing.JButton jButton_My_Jazz;
    private javax.swing.JButton jButton_My_Klasik;
    private javax.swing.JButton jButton_llisteekle;
    private javax.swing.JButton jButton_sarkiekle;
    private javax.swing.JButton jButton_tp_Jazz;
    private javax.swing.JButton jButton_tp_Klasik;
    private javax.swing.JButton jButton_tp_Peru;
    private javax.swing.JButton jButton_tp_Pop;
    private javax.swing.JButton jButton_tp_Turkey;
    private javax.swing.JButton jButton_tp_Usa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_SarkiLİST;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable_Sarkılist;
    private javax.swing.JTextField jTextField_SarkıId;
    private javax.swing.JList<String> users;
    // End of variables declaration//GEN-END:variables

    private void and(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
